title:   Arash Shakibaeian
logo: "/images/photo_2018-06-09_11-05-57.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Welcome to my Business Intelligence Analyst portfolio! As you explore my work, you'll discover how my skills and experiences have contributed to the field of BI. As a BI analyst, I specialize in translating complex data into actionable insights that drive business growth. From data visualization to predictive analytics, I use cutting-edge tools and techniques to help organizations make informed decisions. Please take a moment to browse my portfolio, and feel free to contact me with any questions or inquiries. Thank you for your interest!
  <br>
  <a href="https://www.linkedin.com/in/shakibaeian/">View My LinkedIn Profile</a>
  <br>
  <a href="https://www.tableau.com/products/public">View My Tableau Work Samples</a>
  <br>
  <a href="https://shakibaeian.notion.site/shakibaeian/Portfolio-Arash-Shakibaeian-9a386863ca4d477484e42f732c07999d">View My Notion Portfolios</a>
  <br>
theme: jekyll-theme-minimal
